### ISSUE TITLE
Multiloader example doesn't compile: geckolib-common unavailable, and geckolib-forge, geckolib-fabric and geckolib-neoforge 4.5 don't exist

### ISSUE THREAD

**Issue by brentmaas** [bernie-g/geckolib-examples#4]
I tried to build the Multiloader example in preparation of a project I'll be working on, but the example cannot be built due to missing dependencies. Gradle wants version 4.5 of geckolib-common, geckolib-forge, geckolib-fabric and geckolib-neoforge, but they don't exist.

I can see from, for example, https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/software/bernie/geckolib/geckolib-fabric-1.20.4/maven-metadata.xml that geckolib-fabric does at least exist, but (as of writing) on version 4.4.4 and lower. The same goes for geckolib-forge and geckolib-neoforge. If I try to find geckolib-common in this way, it appears to not exist at all, so I can't simply lower the GeckoLib version to 4.4.4 to get it running.

Since this example repository is fairly new, I suspect that you're about to release version 4.5 and make the geckolib-common package available, but am I correct in that I should be a bit more patient or has something gone wrong?

Also, as a side note, it looks like your Discord invite link has expired, otherwise I would have just asked there.

**Comment by Witixin1512** [comment]
> Since this example repository is fairly new, I suspect that you're about to release version 4.5 and make the geckolib-common package available, but am I correct in that I should be a bit more patient or has something gone wrong?

GeckoLib's MultiLoader release is scheduled for 1.20.5, which should land next week.

GeckoLib 4.5 is not in the maven yet, as a release for 1.20.4 would entail massive breaking changes for developers and end users of the mod. 
In the event you wish to try it yourself, clone [geckolib](https://github.com/bernie-g/geckolib/tree/multiloader-but-for-real-this-time)'s MultiLoader branch and publish the artifacts to mavenLocal using the `publishAllPublicationsToMavenLocalRepository` task. The examples repository adds `mavenLocal()` as a repository, which should allow you to try and build the examples mod. 

As for the Discord link, this one should be valid: https://discord.gg/Bt3p6kA6TK. Could you please link or screenshot where exactly you're seeing the expired link so that someone can fix it eventually? Thanks.

**Comment by brentmaas** [comment]
Ah, that makes sense. I have to target 1.20.1, so we'll stick to separate builds for Forge and Fabric for now then. Thanks!

The place where I found old Discord link is the "Discord X online" button on Modrinth: https://modrinth.com/mod/geckolib. The Patreon button also says "Custom badge inaccessible" to me, but it appears like it should've been replaced by Ko-fi by the looks of the wiki and Curseforge.
